version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      androidx:
        patterns: ["androidx.*", "com.google.android.material:*"]
      pruebas:
        patterns: ["junit:*", "androidx.test*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
